#!/usr/bin/env python

import sys
import math

def factorize(n):
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return i, n // i
    return None, None

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        for line in file:
            number = int(line.strip())
            factor1, factor2 = factorize(number)
            if factor1 is not None and factor2 is not None:
                print("{}={}*{}".format(number, factor1, factor2))

if __name__ == "__main__":
    main()
